remote_theme:	inelaah/rain

# Site settings
title:          BEFLAT
description:    "Rain is a simple and clean Jekyll theme with focus on content."
url:		"https://b2flat.github.io"
baseurl:	""	

# Author
author:		BEFLAT
name:		BEFLAT
email:		b2flat@gmail.com
url:		"https://b2flat.github.io"
baseurl:	""

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
email: bfla2t@gmail.com
github: https://github.com/b2flat

